"""
Django settings for mousemetrics project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# ======================================
# Core paths and environment
# ======================================
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
SECRET_KEY = "django-insecure-$+sao&03^3d2jkya4^a_$x2ea7d-gsx97df@%&q%wq%#&9g)^i"
DEBUG = os.environ.get("MOUSEMETRICS_ENVIRONMENT", "dev").lower() == "dev"

ALLOWED_HOSTS = [
    host for host in os.environ.get("MOUSEMETRICS_HOST", "").split(",") if host
]
CSRF_TRUSTED_ORIGINS = ["https://" + host for host in ALLOWED_HOSTS]

# ======================================
# Installed apps
# ======================================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "anymail",
    "mouseapp",
    "mouse_import",
]

# ======================================
# Middleware
# ======================================
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "mousemetrics.urls"

# ======================================
# Templates
# ======================================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "mousemetrics" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mousemetrics.wsgi.application"

# ======================================
# Database
# ======================================
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": Path(os.environ.get("MOUSEMETRICS_DB_PATH", BASE_DIR / "db.sqlite3")),
    }
}

# ======================================
# Password validation
# ======================================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

AUTHENTICATION_BACKENDS = [
    "mouseapp.backends.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]

ENABLE_REGISTRATION = not bool(os.environ.get("MOUSEMETRICS_DISABLE_REGISTRATION"))

# ======================================
# Internationalization
# ======================================
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# ======================================
# Static files
# ======================================
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "mousemetrics" / "static"]

# ======================================
# Media and file storage
# ======================================
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

STORAGES = {
    # Media (default storage used by FileField, uploads, etc.)
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": MEDIA_ROOT,
            "base_url": MEDIA_URL,
        },
    },
    # Static files storage (served by WhiteNoise in production)
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# ======================================
# Email configuration
# ======================================
RESEND_API_KEY = os.environ.get("RESEND_API_KEY")
EMAIL_BACKEND = (
    "anymail.backends.resend.EmailBackend"
    if RESEND_API_KEY
    else "django.core.mail.backends.console.EmailBackend"
)
DEFAULT_FROM_EMAIL = "Mousemetrics <mousemetrics@mousemetrics.ben.soroos.net>"
SERVER_EMAIL = "Mousemetrics <system@mousemetrics.ben.soroos.net>"

# ======================================
# Authentication redirects
# ======================================
LOGIN_REDIRECT_URL = "mouseapp:home"
LOGIN_URL = "/accounts/login"
LOGOUT_REDIRECT_URL = "/"

# ======================================
# Default PK type
# ======================================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
