[build]
builder = "RAILPACK"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "./start.sh"
sleepApplication = true
useLegacyStacker = false
multiRegionConfig = { "europe-west4-drams3a" = { "numReplicas" = 1 } }
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
