# Generated by Django 5.2.7 on 2025-11-03 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mouseapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MouseImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "file",
                    models.FileField(
                        help_text="Stored under MEDIA_ROOT/mouse_imports/.",
                        upload_to="mouse_imports/",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True,
                        help_text="Original name of the uploaded file.",
                        max_length=255,
                    ),
                ),
                (
                    "sheet_name",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to use the active worksheet.",
                        max_length=128,
                    ),
                ),
                (
                    "cell_range",
                    models.CharField(
                        help_text='Excel range such as "A1:M40".', max_length=32
                    ),
                ),
                ("row_count", models.IntegerField(default=0)),
                ("committed", models.BooleanField(db_index=True, default=False)),
                (
                    "error_log",
                    models.TextField(
                        blank=True, help_text="Captures validation or commit warnings."
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project that owns the imported mice.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mouse_imports",
                        to="mouseapp.project",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="User who uploaded the file.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
