# Generated by Django 5.2.7 on 2025-10-22 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mouse_import", "0001_initial"),
        ("mouseapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="mouseimport",
            name="cell_range",
            field=models.CharField(
                help_text='Excel range such as "A1:M40".', max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="mouseimport",
            name="error_log",
            field=models.TextField(
                blank=True, help_text="Captures validation or commit warnings."
            ),
        ),
        migrations.AlterField(
            model_name="mouseimport",
            name="file",
            field=models.FileField(
                help_text="Stored under MEDIA_ROOT/mouse_imports/.",
                upload_to="mouse_imports/",
            ),
        ),
        migrations.AlterField(
            model_name="mouseimport",
            name="original_filename",
            field=models.CharField(
                blank=True,
                help_text="Original name of the uploaded file.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="mouseimport",
            name="project",
            field=models.ForeignKey(
                help_text="Project that owns the imported mice.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mouse_imports",
                to="mouseapp.project",
            ),
        ),
        migrations.AlterField(
            model_name="mouseimport",
            name="sheet_name",
            field=models.CharField(
                blank=True,
                help_text="Leave blank to use the active worksheet.",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="mouseimport",
            name="uploaded_by",
            field=models.ForeignKey(
                help_text="User who uploaded the file.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
