# Generated by Django 5.2.7 on 2026-02-18 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mouse_import", "0001_mapping_model_state"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="mouseimportmappingexample",
            new_name="mouse_impor_source__e1110b_idx",
            old_name="mi_mapex_hdrfld_idx",
        ),
        migrations.RenameIndex(
            model_name="mouseimportmappingexample",
            new_name="mouse_impor_project_61ec22_idx",
            old_name="mi_mapex_projfld_idx",
        ),
    ]
