# Generated by Django 5.2.7 on 2026-01-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mouse_import", "0002_alter_mouseimport_cell_range_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mouseimport",
            name="original_filename",
            field=models.TextField(
                blank=True, help_text="Original name of the uploaded file."
            ),
        ),
    ]
