# Generated by Django 5.2.7 on 2026-02-03 10:49

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("mouseapp", "0001_initial"),
        ("mouseapp", "0002_alter_box_number_alter_mouse_tube_number"),
        ("mouseapp", "0003_requestreply_studyplan_alter_box_options_and_more"),
        ("mouseapp", "0004_alter_mouse_tube_number_alter_project_name_and_more"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Box",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("permissions", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_constraints", models.TextField()),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leading_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "researchers",
                    models.ManyToManyField(
                        through="mouseapp.Membership",
                        through_fields=("project", "user"),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [("create_project", "Create projects")],
            },
        ),
        migrations.CreateModel(
            name="Mouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("F", "Female"), ("M", "Male")], max_length=1
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("tube_number", models.IntegerField()),
                ("strain", models.TextField()),
                ("coat_colour", models.TextField()),
                ("earmark", models.TextField()),
                ("notes", models.TextField()),
                (
                    "box",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="mouseapp.box"
                    ),
                ),
                (
                    "father",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_set_f",
                        to="mouseapp.mouse",
                    ),
                ),
                (
                    "mother",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_set_m",
                        to="mouseapp.mouse",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mouseapp.project",
                    ),
                ),
            ],
            options={
                "permissions": [("edit_mice", "Can edit mouse details")],
            },
        ),
        migrations.AddField(
            model_name="membership",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mouseapp.project"
            ),
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approved_date", models.DateField(blank=True, null=True)),
                ("fulfill_date", models.DateField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("B", "Breed"), ("C", "Cull")], max_length=1
                    ),
                ),
                ("details", models.TextField()),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("approve_request", "Can approve requests"),
                    ("fulfill_request", "Can mark requests fulfilled"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("project", "user"), name="unique_membership"
            ),
        ),
        migrations.CreateModel(
            name="RequestReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "permissions": [
                    ("send_reply", "Can send replies and queries on requests")
                ],
            },
        ),
        migrations.CreateModel(
            name="StudyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Submitted", "Submitted"),
                            ("Approved", "Approved"),
                            ("Completed", "Completed"),
                        ],
                        default="Draft",
                        max_length=10,
                    ),
                ),
                (
                    "study_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("description", models.TextField()),
                ("approval_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "permissions": [
                    ("approve_study_plan", "Can approve a study plan"),
                    ("view_study_plan", "Can view study plans"),
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="box",
            options={"verbose_name_plural": "Boxes"},
        ),
        migrations.RemoveField(
            model_name="membership",
            name="permissions",
        ),
        migrations.AddField(
            model_name="box",
            name="box_type",
            field=models.CharField(
                choices=[("S", "Shoe"), ("T", "Stock")], default="S", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="box",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="mouseapp.project",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("PROJECT_LEAD", "Project Lead"),
                    ("PROJECT_MEMBER", "Project Member"),
                    ("BREEDING", "Breeding"),
                ],
                default="PROJECT_MEMBER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="allow_over_18_months",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="has_mod_sev_permission",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="project",
            name="quota_5_years",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name="request",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="mouseapp.project",
            ),
        ),
        migrations.AlterField(
            model_name="box",
            name="number",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="mouse",
            name="coat_colour",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mouse",
            name="earmark",
            field=models.CharField(
                blank=True,
                max_length=16,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_earmark",
                        message="Earmark must be a sequence of position codes (T/B for Top/Bottom, R/L for Right/Left). Examples: TR, BL, TRBL.",
                        regex="^([TB][RL])*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="mouse",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="mouse",
            name="tube_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="request",
            name="kind",
            field=models.CharField(
                choices=[
                    ("B", "Set up breeding pair"),
                    ("C", "Cull"),
                    ("T", "Transfer"),
                    ("Q", "Query"),
                ],
                max_length=1,
            ),
        ),
        migrations.AddConstraint(
            model_name="box",
            constraint=models.UniqueConstraint(
                fields=("project", "number"), name="uniq_box_per_project"
            ),
        ),
        migrations.AddConstraint(
            model_name="mouse",
            constraint=models.UniqueConstraint(
                fields=("project", "strain", "tube_number"),
                name="unique_mouse_id_per_project",
            ),
        ),
        migrations.AddField(
            model_name="requestreply",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="mouseapp.request",
            ),
        ),
        migrations.AddField(
            model_name="requestreply",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="studyplan",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_study_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studyplan",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="studyplan",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mouseapp.project"
            ),
        ),
        migrations.AlterField(
            model_name="mouse",
            name="tube_number",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(),
        ),
    ]
