# Generated by Django 5.2.7 on 2025-10-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mouseapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="box",
            name="number",
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="mouse",
            name="tube_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
