# Generated by Django 5.2.7 on 2025-11-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mouseapp", "0003_requestreply_studyplan_alter_box_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mouse",
            name="tube_number",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(),
        ),
    ]
