# Generated by Django 5.2.7 on 2025-11-04 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mouseapp", "0004_alter_mouse_tube_number_alter_project_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="box",
            name="number",
            field=models.CharField(max_length=255),
        ),
    ]
