# Generated by Django 5.2.7 on 2025-11-04 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mouseapp", "0005_alter_box_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membership",
            name="role",
        ),
    ]
