# Generated by Django 5.2.7 on 2025-11-04 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mouseapp", "0006_remove_membership_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="box",
            name="location",
            field=models.CharField(
                choices=[("B", "Breeding"), ("E", "Experimental")],
                default="E",
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mouse",
            name="study_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mice_assigned",
                to="mouseapp.studyplan",
            ),
        ),
        migrations.AddField(
            model_name="studyplan",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studyplan",
            name="mouse_quota_female",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studyplan",
            name="mouse_quota_male",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studyplan",
            name="mouse_source",
            field=models.CharField(
                blank=True, choices=[("I", "Internal"), ("E", "External")], null=True
            ),
        ),
        migrations.AddField(
            model_name="studyplan",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
