# Generated by Django 5.2.7 on 2025-11-10 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mouseapp", "0007_box_location_mouse_study_plan_studyplan_end_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["name"],
                "permissions": [("create_project", "Create projects")],
            },
        ),
    ]
