# Generated by Django 5.2.7 on 2025-11-06 10:28

from django.db import migrations


def migrate_strains(apps, schema_editor):
    Strain = apps.get_model("mouseapp", "Strain")
    Mouse = apps.get_model("mouseapp", "Mouse")
    for mouse in Mouse.objects.all():
        strain, _ = Strain.objects.get_or_create(name=mouse.strain)
        mouse.new_strain = strain
        mouse.save()


class Migration(migrations.Migration):
    dependencies = [
        ("mouseapp", "0008_strain_mouse_new_strain"),
    ]

    operations = [
        migrations.RunPython(migrate_strains),
    ]
