# Generated by Django 5.2.7 on 2025-11-11 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mouseapp", "0008_alter_project_options"),
        ("mouseapp", "0008_alter_request_options_request_created_at_and_more"),
    ]

    operations = []
