# Generated by Django 5.2.7 on 2025-11-06 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mouseapp", "0009_migrate_strains"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="mouse",
            name="unique_mouse_id_per_project",
        ),
        migrations.RemoveField(
            model_name="mouse",
            name="strain",
        ),
        migrations.AlterField(
            model_name="mouse",
            name="new_strain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="mouseapp.strain",
            ),
        ),
        migrations.RenameField(
            model_name="mouse",
            old_name="new_strain",
            new_name="strain",
        ),
        migrations.AddConstraint(
            model_name="mouse",
            constraint=models.UniqueConstraint(
                fields=("project", "strain", "tube_number"),
                name="unique_mouse_id_per_project",
            ),
        ),
    ]
