# Generated by Django 5.2.7 on 2025-11-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mouseapp", "0009_merge_20251111_1722"),
        ("mouseapp", "0011_remove_mouse_new_strain_alter_mouse_strain"),
    ]

    operations = []
