# Generated by Django 5.2.7 on 2025-11-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mouseapp", "0011_remove_mouse_new_strain_alter_mouse_strain"),
    ]

    operations = [
        migrations.AddField(
            model_name="mouse",
            name="cull_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mouse",
            name="cull_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
