# Generated by Django 5.2.7 on 2025-11-21 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mouseapp", "0012_merge_20251117_1340"),
        ("mouseapp", "0012_mouse_cull_date_mouse_cull_reason_alter_mouse_strain"),
    ]

    operations = []
