# Generated by Django 5.2.7 on 2025-11-23 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mouseapp", "0013_merge_20251121_2307"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mouse",
            name="strain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="mouseapp.strain",
            ),
        ),
    ]
