# Generated by Django 5.2.7 on 2026-01-29 11:22

from django.db import migrations


def update_fields(apps, _scheme_editor):
    StudyPlan = apps.get_model("mouseapp", "StudyPlan")
    Request = apps.get_model("mouseapp", "Request")

    for study_plan in StudyPlan.objects.all():
        match study_plan.status:
            case "Draft":
                study_plan.status = "D"
            case "Submitted":
                study_plan.status = "S"
            case "Approved":
                study_plan.status = "A"
            case "Completed":
                study_plan.status = "C"
        study_plan.save()

    for request in Request.objects.all():
        match request.status:
            case "pending":
                request.status = "P"
            case "accepted":
                request.status = "A"
            case "denied":
                request.status = "D"
            case "completed":
                request.status = "C"
        request.save()


class Migration(migrations.Migration):

    dependencies = [
        ("mouseapp", "0014_alter_mouse_strain"),
    ]

    operations = [migrations.RunPython(update_fields)]
