# Generated by Django 5.2.7 on 2026-01-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mouseapp", "0015_update_choice_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="box",
            name="number",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("A", "Accepted"),
                    ("D", "Denied"),
                    ("C", "Completed"),
                ],
                default="P",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="studyplan",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="studyplan",
            name="mouse_source",
            field=models.CharField(
                blank=True,
                choices=[("I", "Internal"), ("E", "External")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="studyplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("D", "Draft"),
                    ("S", "Submitted"),
                    ("A", "Approved"),
                    ("C", "Completed"),
                ],
                default="Draft",
                max_length=1,
            ),
        ),
    ]
