# Generated by Django 5.2.7 on 2026-01-31 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mouseapp", "0017_replyreaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestreply",
            name="quoted_reply",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quoted_by",
                to="mouseapp.requestreply",
            ),
        ),
    ]
