# Generated by Django 5.2.7 on 2026-01-31 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mouseapp", "0018_requestreply_quoted_reply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestreply",
            name="quoted_reply",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mouseapp.requestreply",
            ),
        ),
    ]
