# Generated by Django 5.2.7 on 2026-03-10 10:34

from django.db import migrations
from django.contrib.auth.management import create_permissions
from django.apps import apps as global_apps


def create_animal_facility_group(apps, schema_editor):
    db = schema_editor.connection.alias

    # This usually gets run on a post-migrate hook, meaning we can't rely
    # on permissions existing here
    create_permissions(global_apps.get_app_config("mouseapp"), using=db, verbosity=1)

    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    contenttypes = ContentType.objects.db_manager(using=db)
    project = contenttypes.get_for_model(apps.get_model("mouseapp", "Project"))
    study_plan = contenttypes.get_for_model(apps.get_model("mouseapp", "StudyPlan"))
    request = contenttypes.get_for_model(apps.get_model("mouseapp", "Request"))

    group = Group.objects.using(db).create(name="Animal Facility User")
    permissions = Permission.objects.using(db)
    group.permissions.set(
        [
            permissions.get(content_type=project, codename="manage_projects"),
            permissions.get(content_type=project, codename="add_project"),
            permissions.get(content_type=study_plan, codename="approve_study_plan"),
            permissions.get(content_type=study_plan, codename="view_study_plan"),
            permissions.get(content_type=request, codename="approve_request"),
            permissions.get(content_type=request, codename="fulfill_request"),
        ]
    )
    group.save()


def drop_animal_facility_group(apps, schema_editor):
    apps.get_model("auth", "Group").objects.using(
        schema_editor.connection.alias
    ).filter(name="Animal Facility User").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("mouseapp", "0019_alter_requestreply_quoted_reply"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("create_project", "Create projects"),
                    ("manage_projects", "Manage projects"),
                ],
            },
        ),
        migrations.RunPython(create_animal_facility_group, drop_animal_facility_group),
    ]
