# Generated by Django 5.2.7 on 2026-02-26 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mouseapp", "0019_alter_requestreply_quoted_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="reply",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="mouseapp.requestreply",
            ),
        ),
    ]
