# Generated by Django 5.2.7 on 2026-03-22 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mouseapp", "0020_alter_project_options"),
        ("mouseapp", "0020_notification_reply"),
    ]

    operations = []
