# Generated by Django 5.2.7 on 2026-03-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mouseapp", "0020_notification_reply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studyplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("D", "Draft"),
                    ("S", "Submitted"),
                    ("A", "Approved"),
                    ("C", "Completed"),
                ],
                default="D",
                max_length=1,
            ),
        ),
    ]
