# Generated by Django 5.2.7 on 2026-03-24 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mouseapp", "0021_alter_studyplan_status"),
        ("mouseapp", "0021_merge_20260322_1840"),
    ]

    operations = []
