# Generated by Django 5.2.7 on 2026-03-26 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mouseapp", "0022_merge_20260324_2055"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MouseObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PH", "Phenotype"),
                            ("ML", "Missing Limbs"),
                            ("MA", "Missing Appendages"),
                            ("CE", "Cloudy Eyes"),
                            ("RT", "Ring Tail"),
                            ("KT", "Kinky Tail"),
                            ("CT", "Curly Tail"),
                            ("CM", "Coat Missing"),
                            ("OT", "Overgrown Teeth"),
                            ("", "Other"),
                        ],
                        default="",
                        max_length=2,
                        null=True,
                    ),
                ),
                ("details", models.TextField(blank=True, null=True)),
                (
                    "mouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="mouseapp.mouse",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
