# Generated by Django 5.2.7 on 2026-04-05 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mouseapp", "0023_mouseobservation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genotype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name="mouse",
            old_name="cull_date",
            new_name="death_date",
        ),
        migrations.RenameField(
            model_name="mouse",
            old_name="cull_reason",
            new_name="death_reason",
        ),
        migrations.AddField(
            model_name="mouse",
            name="death_cause",
            field=models.CharField(
                blank=True,
                choices=[("C", "Cull"), ("N", "Natural"), ("O", "Other")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mouse",
            name="genotype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="mouseapp.genotype",
            ),
        ),
    ]
