# Generated by Django 5.2.7 on 2026-04-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mouseapp", "0024_genotype_rename_cull_date_mouse_death_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mouseobservation",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PH", "Phenotype"),
                    ("ML", "Missing Limbs"),
                    ("MA", "Missing Appendages"),
                    ("CE", "Cloudy Eyes"),
                    ("RT", "Ring Tail"),
                    ("KT", "Kinky Tail"),
                    ("CT", "Curly Tail"),
                    ("CM", "Coat Missing"),
                    ("OT", "Overgrown Teeth"),
                    ("", "Other"),
                ],
                default="",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="replyreaction",
            name="emoji",
            field=models.CharField(max_length=4),
        ),
    ]
